---
- name: Provision ec2 instances
  hosts: all
  connection: local
  gather_facts: true

  tasks:

  - name: launch instances
    ec2: 
      region: "US West (N. California)"
      ec2_access_key: "AKIAIMW257B4DJVYH2ZA"
      ec2_secret_key: "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"
      keypair: "tcs.ms.poc"
      group: ""
      instance_type: "t2.micro"
      image: ""
      instance_tags: "tcspocmsansiblepoccai1"
      exact_count: "1"
      count_tag: "1"
      wait: true
    register: ec2
    with_items: ec2_instances