---
- name: Provision ec2 instances
  hosts: all
  connection: local
  gather_facts: true

  tasks:

  - name: launch instances
    ec2: 
      region: "us-west-1"
      ec2_access_key: "AKIAIMW257B4DJVYH2ZA"
      ec2_secret_key: "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"
      keypair: "tcs-poc-ms-ansible"
      instance_type: "t2.micro"
      instance_tags:
        Name: "tcspocmsansiblepoccai1"
        Service: "tcspocmsansiblepoccai1svc"
      exact_count: "1"
      count_tag: "1"
      image: ""
      wait: true
    register: ec2
    with_items: ec2_instances
